export interface Item {
    id:number; 
    marca: string;
    nombre: string; 
    descripcion: string;
    conectividad: string;
    RAM: string;
    procesador: string;
    bateria: string;
    ancho: string;
    precio: string; 
    recomendaciones:Array<number>;
}

export let ListaItems:Array<Item>=[
    {
        id:1,
        marca: "APPLE",
        nombre: "iPhone 11 64GB Blanco",
        descripcion: "iPhone Apple 11 con tecnologia IP68 resiste hasta 2 metros de profundidad durante un maximo de 30 minutos",
        conectividad: "Bluetooth 5.0 / Wifi 802.11ax con MIMO 2x2",
        RAM: "4GB",
        procesador: "Hexa Core",
        bateria: "3110 mAh",
        ancho: "7.57 cm",
        precio: "529.000",
        recomendaciones: [5,7,9],
    },
    {
        id:2,
        marca: "SONY",
        nombre: "Playstation 4 500GB",
        descripcion: "Playstation 4 500GB con tecnologia IP68 resiste hasta 2 metros de profundidad durante un maximo de 30 minutos",
        conectividad: "Bluetooth 5.0 / Wifi 802.11ax con MIMO 2x2",
        RAM: "4GB",
        procesador: "Hexa Core",
        bateria: "3110 mAh",
        ancho: "7.57 cm",
        precio: "529.000",
        recomendaciones: [3,6,11],
    },
    {
        id:3,
        marca: "SONY",
        nombre: "Playstation 4 500GB",
        descripcion: "Playstation 4 500GB con tecnologia IP68 resiste hasta 2 metros de profundidad durante un maximo de 30 minutos",
        conectividad: "Bluetooth 5.0 / Wifi 802.11ax con MIMO 2x2",
        RAM: "4GB",
        procesador: "Hexa Core",
        bateria: "3110 mAh",
        ancho: "7.57 cm",
        precio: "529.000",
        recomendaciones: [2,6,11],
    },
    {
        id:4,
        marca: "LENOVO",
        nombre: "Lenovo Y700",
        descripcion: "Lenovo Y700 con tecnologia IP68 resiste hasta 2 metros de profundidad durante un maximo de 30 minutos",
        conectividad: "Bluetooth 5.0 / Wifi 802.11ax con MIMO 2x2",
        RAM: "4GB",
        procesador: "Hexa Core",
        bateria: "3110 mAh",
        ancho: "7.57 cm",
        precio: "329.000",
        recomendaciones: [8,10,12],
    },
    {
        id:5,
        marca: "APPLE",
        nombre: "iPhone 11 256GB Blanco",
        descripcion: "iPhone Apple 11 con tecnologia IP68 resiste hasta 2 metros de profundidad durante un maximo de 30 minutos",
        conectividad: "Bluetooth 5.0 / Wifi 802.11ax con MIMO 2x2",
        RAM: "4GB",
        procesador: "Hexa Core",
        bateria: "3110 mAh",
        ancho: "7.57 cm",
        precio: "229.000",
        recomendaciones: [1,7,9],
    },
    {
        id:6,
        marca: "SONY",
        nombre: "Playstation 4 500GB",
        descripcion: "Playstation 4 500GB con tecnologia IP68 resiste hasta 2 metros de profundidad durante un maximo de 30 minutos",
        conectividad: "Bluetooth 5.0 / Wifi 802.11ax con MIMO 2x2",
        RAM: "4GB",
        procesador: "Hexa Core",
        bateria: "3110 mAh",
        ancho: "7.57 cm",
        precio: "929.000",
        recomendaciones: [2,3,11],
    },
    {
        id:7,
        marca: "APPLE",
        nombre: "iPhone 11 64GB Blanco",
        descripcion: "iPhone Apple 11 con tecnologia IP68 resiste hasta 2 metros de profundidad durante un maximo de 30 minutos",
        conectividad: "Bluetooth 5.0 / Wifi 802.11ax con MIMO 2x2",
        RAM: "4GB",
        procesador: "Hexa Core",
        bateria: "3110 mAh",
        ancho: "7.57 cm",
        precio: "829.000",
        recomendaciones: [1,5,9],
    },
    {
        id:8,
        marca: "LENOVO",
        nombre: "Lenovo Y700",
        descripcion: "Lenovo Y700 con tecnologia IP68 resiste hasta 2 metros de profundidad durante un maximo de 30 minutos",
        conectividad: "Bluetooth 5.0 / Wifi 802.11ax con MIMO 2x2",
        RAM: "4GB",
        procesador: "Hexa Core",
        bateria: "3110 mAh",
        ancho: "7.57 cm",
        precio: "429.000",
        recomendaciones: [4,10,12],
    },
    {
        id:9,
        marca: "APPLE",
        nombre: "iPhone 11 128GB Rojo",
        descripcion: "iPhone Apple 11 con tecnologia IP68 resiste hasta 2 metros de profundidad durante un maximo de 30 minutos",
        conectividad: "Bluetooth 5.0 / Wifi 802.11ax con MIMO 2x2",
        RAM: "4GB",
        procesador: "Hexa Core",
        bateria: "3110 mAh",
        ancho: "7.57 cm",
        precio: "529.000",
        recomendaciones: [1,5,7],
    },
    {
        id:10,
        marca: "LENOVO",
        nombre: "Lenovo Y300",
        descripcion: "Lenovo Y300 con tecnologia IP68 resiste hasta 2 metros de profundidad durante un maximo de 30 minutos",
        conectividad: "Bluetooth 5.0 / Wifi 802.11ax con MIMO 2x2",
        RAM: "4GB",
        procesador: "Hexa Core",
        bateria: "3110 mAh",
        ancho: "7.57 cm",
        precio: "529.000",
        recomendaciones: [4,8,12],
    },
    {
        id:11,
        marca: "SONY",
        nombre: "Playstation 4 1TB",
        descripcion: "Playstation 4 1TB con tecnologia IP68 resiste hasta 2 metros de profundidad durante un maximo de 30 minutos",
        conectividad: "Bluetooth 5.0 / Wifi 802.11ax con MIMO 2x2",
        RAM: "4GB",
        procesador: "Hexa Core",
        bateria: "3110 mAh",
        ancho: "7.57 cm",
        precio: "629.000",
        recomendaciones: [2,3,6],
    },
    {
        id:12,
        marca: "LENOVO",
        nombre: "Lenovo Y500",
        descripcion: "Lenovo Y500 con tecnologia IP68 resiste hasta 2 metros de profundidad durante un maximo de 30 minutos",
        conectividad: "Bluetooth 5.0 / Wifi 802.11ax con MIMO 2x2",
        RAM: "4GB",
        procesador: "Hexa Core",
        bateria: "3110 mAh",
        ancho: "7.57 cm",
        precio: "429.000",
        recomendaciones: [4,8,10],
    }
]
